title: Jason Liu – Robotics & Automation
logo: /assets/img/logo.png
description: Personal portfolio and projects.
show_downloads: false
google_analytics:
# theme: jekyll-theme-minimal   ← optional, now commented
